### PR TITLE
Remove hipchat notifications from Travis CI

### PR DESCRIPTION
**Pull request by kylef**
We don't use HipChat anymore.

### CODE REVIEW

**Comment by pksunkara** [comment]
Please don't forget to add slack if you are removing hip chat.

**Comment by w-vi** [comment]
No need to add it in `cicrcle.yml` it is set up using the slack integration directly

**Comment by pksunkara** [comment]
But as you can see in this repository, we don't have a circle.yml. Not all of our repos are being tested by circleCI.

**Comment by w-vi** [comment]
Sorry I missed that in this case it is Travis.

**Pull request merged**
